version: '3.7'

services:
  db:
    image: postgres:alpine
    env_file: .env

  app:
    image: $REPOSITORY_IMAGE:$CIRCLE_SHA1
    command: bash -c "bundle exec rspec"
    env_file: .env
    ports:
      - '3000:3000'
    depends_on:
      - db
