version: '3.7'

services:
  db:
    image: postgres:alpine
    env_file: .env
    volumes:
      - db-data:/var/lib/postgresql/db-data

  app:
    build: .
    command: bash -c "bundle exec puma -C config/puma.rb"
    env_file: .env
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - .:/app
      - ./public/uploads:/app/public/uploads
      - bundle_cache:/bundle

volumes:
  db-data:
    external: false
  bundle_cache:
    external: false
